[application]
name = "open-mcp-manager"
default_platform = "desktop"

[bundle]
identifier = "dev.millsy.openmcpmanager"
icon = ["public/icon.png"]
category = "Productivity"
resources = ["public/*"]

[desktop]
window_resizable = true
window_title = "Open MCP Manager"
window_width = 1200
window_height = 800
